name: seek_qr_app
repository: https://github.com/jcuevashub/seek_qr_app

packages:
  - apps
  - packages/qr_scanner
  - packages/auth_biometrics

scripts:
  bootstrap: melos bootstrap
  analyze: melos run analyze
  test:
    run: melos exec --dir-exists=test --flutter -- flutter test
    description: Run Flutter tests in all packages with a 'test' directory.
  format: melos run format

command:
  bootstrap:
    runPubGetInParallel: true
