name: qr_scanner
description: Modulo para escaneo de códigos QR.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  app_common:
    path: ../app_common
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true